### ISSUE TITLE
Clean up codebase (refactoring)

### ISSUE THREAD

**Issue by luca-martial** [JohnSnowLabs/nlptest#194]
@JulesBelveze please lead this task, @chakravarthik27 is working on other tasks and may join you at some point, so please try to make your plan public so he can jump in at anytime (he'll communicate with you before jumping in anyways)

**Comment by JulesBelveze** [comment]
Sweet, I'll draft a plan and share it with you by tomorrow

**Comment by JulesBelveze** [comment]
Here are the main tasks I found so far:
- refacto `Sample` object
- remove commented blocks
- address TODOs
- fix tests
- make sure that we use the same approach for all children objects (e.g. some model handlers use data frames others `List[Sample]`
- check return types
- add missing docstrings
- some code blocks can be re-written in more elegant ways
- optimize imports
- lint code
- JSL check `is_classifier` method
