### ISSUE TITLE
Remove download progress bars from transformers model downloads

### ISSUE THREAD

**Issue by luca-martial** [JohnSnowLabs/nlptest#259]
This is for the gender classifier download when users call those related tests. It is also for when users initialize a harness with a transformers model

**Comment by chakravarthik27** [comment]
@luca-martial 

it is impossible to disable progress bars in transformers.

an alternative way to resolve it, we can download models before or in harness class

`from huggingface_hub import hf_hub_download
hf_hub_download(repo_id="sentence-transformers/all-MiniLM-L6-v2", filename="config.json")`

**Comment by luca-martial** [comment]
> @luca-martial 
> 
> it is impossible to disable progress bars in transformers.
> 
> an alternative way to resolve it, we can download models before or in harness class
> 
> `from huggingface_hub import hf_hub_download`
> `hf_hub_download(repo_id="sentence-transformers/all-MiniLM-L6-v2", filename="config.json")`

Thanks for looking into it @chakravarthik27 I'll close this issue as not planned then!
