### ISSUE TITLE
Can't load custom NER model

### ISSUE THREAD

**Issue by dreji18** [JohnSnowLabs/nlptest#311]
Hi, Thank you all for this great work.

I was trying my custom model with this package. But I am unable to load them. I am getting the value error
```
ValueError: You haven't specified any value for the parameter 'data' and the 
configuration you passed is not among the default ones. You need to either 
specify the parameter 'data' or use a default configuration.
```
```python
from nlptest import Harness
h1 = Harness(task='ner', model='d4data/biomedical-ner-all', hub='huggingface')
out_ = h1.generate().run().report()
```

**Comment by luca-martial** [comment]
Thanks for opening the first community issue @dreji18 ! As the value error suggests, you need to pass the `data` parameter when using a custom model. The examples we have on the repo and website use default datasets that are specific to the models (this is so you can quickly test out the library). But any other models will require passing a dataset with entity classes that the model is familiar with (you cannot use the default datasets when passing custom models). That dataset can be in CoNLL format or in csv format, here are more details: https://nlptest.org/docs/pages/docs/data_input

Let me know if this helps!
