### ISSUE TITLE
Add a `conda` install option for `nlptest` on conda-forge channel

### ISSUE THREAD

**Issue by sugatoray** [JohnSnowLabs/nlptest#318]
A conda installation option from `conda-forge` channel could be very helpful for all downstream packages that depend on `nlptest`. I have already started working on this, to add `nlptest` to conda-forge.

Conda-forge PR: 

- https://github.com/conda-forge/staged-recipes/pull/22525

Once the conda-forge PR is merged, you will be able to install the library with conda as follows:

```sh
conda install -c conda-forge nlptest
```

:bulb: I will push a PR to update the docs once the package is available on conda-forge.

**Comment by ArshaanNazir** [comment]
Hi @sugatoray , thanks a lot for your contribution.  Once the package is available, let us know.

**Comment by sugatoray** [comment]
@ArshaanNazir Sure. Will do. 

:bulb: It will be nice to co-maintain the conda-forge package with core-contributors of `nlptest`. Please let me know who I could add as co-maintainer to the conda-forge feedstock, once the package is added to conda-forge channel.

#elf-assign

**Comment by luca-martial** [comment]
Thanks so much for these contributions @sugatoray !! Could you please add `johnsnowlabs` as co-maintainer once the package is added: https://anaconda.org/johnsnowlabs

Also please note that we are working on removing the `wn` dependency for the upcoming `v1.0.2` release, see here: https://github.com/JohnSnowLabs/nlptest/issues/310

**Comment by sugatoray** [comment]
@luca-martial Thank you. Conda-Forge maintainers are typically GitHub users. I am not sure if we can have `johnsnowlabs` as a GitHub user. But since, the owner of `nlptest` is `@johnsnowlab`, will try adding @JohnSnowLab as the co-maintainer.

**Comment by sugatoray** [comment]
Good news! The PR has been merged. :tada:

So, `nlptest` will be soon available on conda-forge.

I have added @johnsnowlabs and @luca-martial as co-maintainers in the feedstock repo: 
- https://github.com/conda-forge/nlptest-feedstock.

Expect to see the recipe on conda-forge in next 2-3 hours.

- URL: https://anaconda.org/conda-forge/nlptest
- Command: `conda search -c conda-forge nlptest`
