### ISSUE TITLE
Add support for dyslexia test

### ISSUE THREAD

**Issue by luca-martial** [JohnSnowLabs/nlptest#344]
Integrate the following module in nlptest for NER and text classification: https://github.com/GEM-benchmark/NL-Augmenter/tree/main/nlaugmenter/transformations/dyslexia_words_swap

It will fall under the Robustness category

Make sure to watch out for changes in Span start and end indexes when swapping words

**Comment by ArkajyotiChakraborty** [comment]
Added a PR for the issue, here: https://github.com/JohnSnowLabs/nlptest/pull/417#issue-1708544964
