### ISSUE TITLE
Add a method to run comparisons between different models from same/different hubs

### ISSUE THREAD

**Issue by luca-martial** [JohnSnowLabs/nlptest#387]

**Comment by ArshaanNazir** [comment]
model 		      | Hub | 	     |Test-name|   

ner.dl                        jsl                      0.8            > Green/Red if it passed for fail
en_core_web_sm        spacy              0.7

**Comment by ArshaanNazir** [comment]
If the test passes, format test column cell with green background. Otherwise red.
