### ISSUE TITLE
False Negative Results in swap_entities robustness Test

### ISSUE THREAD

**Issue by RakshitKhajuria** [JohnSnowLabs/nlptest#424]
Expected and Actual Results Match but Test Fails.
When I reran the models again, sometimes it showed these results for 'bert-base-NER' and not for spacy model and sometimes it showed for spacy model and not 'bert-base-NER' .
![MicrosoftTeams-image](https://github.com/JohnSnowLabs/nlptest/assets/71117423/177f14b7-72a3-402c-af8b-bc471febcbec)

**Comment by dcecchini** [comment]
Problem is not on NLP Test.
